name: VanillinSMPCore
version: '${project.version}'
main: me.applesfruit.vanillinsmp.VanillinSMP
api-version: 1.19
authors: [ applesfruit ]
commands:
  message:
    aliases: ["msg", "w"]
    description: Send someone a message.
  reply:
    aliases: ["r"]
    description: Reply to the person you have had the most recent conversation with.
  afk:
    description: Away from keyboard.
  mutechat:
    description: THE SERVER HAVE BEEN SILENCED!
  clearchat:
    description: POOF! CHAT HAS DISAPPEARED.
  ban:
    description: haha, YOU HAVE BEEN PERMANENTLY BANNED FROM VANILLINSMP. GOOD RIDDANCE
  rank:
    description: woah! i am admin now?
  unban:
    description: AAAAAHHHHHHHHHHHHHH im tired of making these descriptions. this just unbans people
  about:
    description: about ur mom
  rules:
    description: dont breka them, or else....
  warn:
    description: oops, what have you done?
  warns:
    description: how many warns do you have? hmmm??????? 3RD WARN? YOU GET MUTE!!!
  donate:
    description: please support the server ty
  mute:
    description: you have been silenced
  chatcolor:
    description: WOAH CHAT COLORS?????